# Generated by Django 6.0.3 on 2026-04-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_created_at_remove_project_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
